"""empty message

Revision ID: 11e87680d6fe
Revises: 4a4eb5cce66f
Create Date: 2019-09-13 16:13:19.793084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11e87680d6fe'
down_revision = '4a4eb5cce66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
