"""empty message

Revision ID: 2afa51da4fe9
Revises: 4f60b6004fe6
Create Date: 2019-09-11 18:55:35.047127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2afa51da4fe9"
down_revision = "4f60b6004fe6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_role",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("token")
    op.drop_constraint("user_permission_slug_project_id_key", "user_permission", type_="unique")
    op.drop_constraint("user_permission_project_id_fkey", "user_permission", type_="foreignkey")
    op.drop_column("user_permission", "project_id")
    op.add_column("user_permission_linker", sa.Column("project_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "user_permission_linker", ["permission_id", "user_id", "project_id"])
    op.create_foreign_key(None, "user_permission_linker", "project", ["project_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_permission_linker", type_="foreignkey")
    op.drop_constraint(None, "user_permission_linker", type_="unique")
    op.drop_column("user_permission_linker", "project_id")
    op.add_column("user_permission", sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key("user_permission_project_id_fkey", "user_permission", "project", ["project_id"], ["id"])
    op.create_unique_constraint("user_permission_slug_project_id_key", "user_permission", ["slug", "project_id"])
    op.create_table(
        "token",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True
        ),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="token_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="token_pkey"),
        sa.UniqueConstraint("value", name="token_value_key"),
    )
    op.drop_table("user_role")
    # ### end Alembic commands ###
