"""empty message

Revision ID: 4a4eb5cce66f
Revises: c1dfc4e676c0
Create Date: 2019-09-13 15:57:52.406542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a4eb5cce66f'
down_revision = 'c1dfc4e676c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('project', sa.Column('domain_id', sa.Integer(), nullable=False))
    op.add_column('project', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(None, 'project', ['slug'])
    op.create_foreign_key(None, 'project', 'domain', ['domain_id'], ['id'])
    op.drop_column('project', 'is_deactivated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_deactivated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'uuid')
    op.drop_column('project', 'is_active')
    op.drop_column('project', 'domain_id')
    op.drop_table('domain')
    # ### end Alembic commands ###
