"""empty message

Revision ID: 4f60b6004fe6
Revises: 9a42786518a1
Create Date: 2019-09-05 16:22:21.062039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f60b6004fe6"
down_revision = "9a42786518a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("is_deactivated", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "is_deactivated")
    # ### end Alembic commands ###
