"""empty message

Revision ID: 513e87a4d317
Revises: fb0fc7b0e585
Create Date: 2019-09-13 16:33:20.195083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '513e87a4d317'
down_revision = 'fb0fc7b0e585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_permission')
    op.drop_constraint('user_permission_linker_permission_id_fkey', 'user_permission_linker', type_='foreignkey')
    op.create_foreign_key(None, 'user_permission_linker', 'permission', ['permission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permission_linker', type_='foreignkey')
    op.create_foreign_key('user_permission_linker_permission_id_fkey', 'user_permission_linker', 'user_permission', ['permission_id'], ['id'])
    op.create_table('user_permission',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_permission_pkey')
    )
    op.drop_table('permission')
    # ### end Alembic commands ###
