"""empty message

Revision ID: fb0fc7b0e585
Revises: 11e87680d6fe
Create Date: 2019-09-13 16:21:00.273808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb0fc7b0e585'
down_revision = '11e87680d6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
